services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: flynextDB_user
      POSTGRES_PASSWORD: fly123
      POSTGRES_DB: FlyNext
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  populate:
    build:
      context: .
      dockerfile: Dockerfile.populate
    container_name: populate_service
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://flynextDB_user:fly123@postgres:5432/FlyNext
    command: >
      sh -c "npx prisma migrate deploy && node src/utils/runPopulate.js"
    profiles:
      - populate

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: >
      sh -c "npx prisma migrate && npx prisma generate && npm start"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  postgres_data: