# Use the same base image as the main application
FROM node:20-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy only the necessary files for the populate service
COPY package.json package-lock.json ./
COPY prisma ./prisma
COPY src/utils ./src/utils
COPY importData ./importData 

# Install dependencies
RUN npm install

# Generate the Prisma client
RUN npx prisma generate

# Default command for the populate service
CMD ["node", "src/utils/runPopulate.js"]