services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: flynextDB_user
      POSTGRES_PASSWORD: fly123
      POSTGRES_DB: FlyNext
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  populate:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: populate_service
      depends_on:
        - postgres
      environment:
        DATABASE_URL: postgresql://flynextDB_user:fly123@postgres:5432/FlyNext
      command: >
        sh -c "ls -la && pwd && npx prisma generate && node src/utils/runPopulate.js"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - populate
    command: >
      sh -c "npx prisma generate && npx prisma migrate deploy && npm start"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  postgres_data: